apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-testapi-green
  labels:
    prod_tag: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      node_tag: testapi
  template:
    metadata:
      name: testapi-pod
      labels:
        node_tag: testapi
    spec:
      containers:
        - name: prod-testapi
#          image: backendsandbox.azurecr.io/helloworldrestapi01:007dbc2e851be4f23f063cdfea5970a2af0ac4ac
#          imagePullPolicy: IfNotPresent
          image: backendsandbox.azurecr.io/helloworldrestapi01:022a9554d77163cfff2ab57ec2abfcc9a99114b8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
      imagePullSecrets:
        - name: helloworldrestapi01
