apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-testapi-green
  labels:
    prod_tag: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      node_tag: testapi
  template:
    metadata:
      name: testapi-pod
      labels:
        node_tag: testapi
    spec:
      containers:
        - name: prod-testapi
          image: backendsandbox.azurecr.io/helloworldrestapi01:d0f8147983eae629eff3b3a77380156c34313428
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
      imagePullSecrets:
        - name: helloworldrestapi01
