name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: backendsandbox.azurecr.io
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}
    - run:
        docker build . -f docker/Dockerfile -t backendsandbox.azurecr.io/helloworldrestapi01:${{ github.sha }}
        docker push backendsandbox.azurecr.io/helloworldrestapi01:${{ github.sha }}
